/*
 * This file is generated by jOOQ.
 */
package com.parser.core.example.entity.tables;


import com.parser.core.example.entity.Keys;
import com.parser.core.example.entity.Public;
import com.parser.core.example.entity.tables.records.TestEntityRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestEntity extends TableImpl<TestEntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.test_entity</code>
     */
    public static final TestEntity TEST_ENTITY = new TestEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestEntityRecord> getRecordType() {
        return TestEntityRecord.class;
    }

    /**
     * The column <code>public.test_entity.id</code>.
     */
    public final TableField<TestEntityRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.test_entity.name</code>.
     */
    public final TableField<TestEntityRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    private TestEntity(Name alias, Table<TestEntityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TestEntity(Name alias, Table<TestEntityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.test_entity</code> table reference
     */
    public TestEntity(String alias) {
        this(DSL.name(alias), TEST_ENTITY);
    }

    /**
     * Create an aliased <code>public.test_entity</code> table reference
     */
    public TestEntity(Name alias) {
        this(alias, TEST_ENTITY);
    }

    /**
     * Create a <code>public.test_entity</code> table reference
     */
    public TestEntity() {
        this(DSL.name("test_entity"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TestEntityRecord, Integer> getIdentity() {
        return (Identity<TestEntityRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TestEntityRecord> getPrimaryKey() {
        return Keys.TEST_ENTITY_PKEY;
    }

    @Override
    public TestEntity as(String alias) {
        return new TestEntity(DSL.name(alias), this);
    }

    @Override
    public TestEntity as(Name alias) {
        return new TestEntity(alias, this);
    }

    @Override
    public TestEntity as(Table<?> alias) {
        return new TestEntity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TestEntity rename(String name) {
        return new TestEntity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestEntity rename(Name name) {
        return new TestEntity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestEntity rename(Table<?> name) {
        return new TestEntity(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestEntity where(Condition condition) {
        return new TestEntity(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestEntity where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestEntity where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestEntity where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestEntity where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestEntity where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestEntity where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestEntity where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestEntity whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestEntity whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
