/*
 * This file is generated by jOOQ.
 */
package com.parser.core.example.entity.tables.records;


import com.parser.core.example.entity.tables.ExampleDict;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExampleDictRecord extends UpdatableRecordImpl<ExampleDictRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.example_dict.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.example_dict.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.example_dict.cdt</code>.
     */
    public void setCdt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.example_dict.cdt</code>.
     */
    public LocalDateTime getCdt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.example_dict.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.example_dict.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.example_dict.mdt</code>.
     */
    public void setMdt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.example_dict.mdt</code>.
     */
    public LocalDateTime getMdt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.example_dict.modified_by</code>.
     */
    public void setModifiedBy(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.example_dict.modified_by</code>.
     */
    public UUID getModifiedBy() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.example_dict.rdt</code>.
     */
    public void setRdt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.example_dict.rdt</code>.
     */
    public LocalDateTime getRdt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.example_dict.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.example_dict.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.example_dict.name</code>.
     */
    public void setName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.example_dict.name</code>.
     */
    public String getName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.example_dict.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.example_dict.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.example_dict.date</code>.
     */
    public void setDate(LocalDate value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.example_dict.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(9);
    }

    /**
     * Setter for <code>public.example_dict.date_time</code>.
     */
    public void setDateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.example_dict.date_time</code>.
     */
    public LocalDateTime getDateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.example_dict.number</code>.
     */
    public void setNumber(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.example_dict.number</code>.
     */
    public Long getNumber() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.example_dict.text</code>.
     */
    public void setText(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.example_dict.text</code>.
     */
    public String getText() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.example_dict.time</code>.
     */
    public void setTime(LocalTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.example_dict.time</code>.
     */
    public LocalTime getTime() {
        return (LocalTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExampleDictRecord
     */
    public ExampleDictRecord() {
        super(ExampleDict.EXAMPLE_DICT);
    }

    /**
     * Create a detached, initialised ExampleDictRecord
     */
    public ExampleDictRecord(UUID id, LocalDateTime cdt, UUID createdBy, LocalDateTime mdt, UUID modifiedBy, LocalDateTime rdt, String description, String name, BigDecimal amount, LocalDate date, LocalDateTime dateTime, Long number, String text, LocalTime time) {
        super(ExampleDict.EXAMPLE_DICT);

        setId(id);
        setCdt(cdt);
        setCreatedBy(createdBy);
        setMdt(mdt);
        setModifiedBy(modifiedBy);
        setRdt(rdt);
        setDescription(description);
        setName(name);
        setAmount(amount);
        setDate(date);
        setDateTime(dateTime);
        setNumber(number);
        setText(text);
        setTime(time);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ExampleDictRecord
     */
    public ExampleDictRecord(com.parser.core.example.entity.tables.pojos.ExampleDict value) {
        super(ExampleDict.EXAMPLE_DICT);

        if (value != null) {
            setId(value.getId());
            setCdt(value.getCdt());
            setCreatedBy(value.getCreatedBy());
            setMdt(value.getMdt());
            setModifiedBy(value.getModifiedBy());
            setRdt(value.getRdt());
            setDescription(value.getDescription());
            setName(value.getName());
            setAmount(value.getAmount());
            setDate(value.getDate());
            setDateTime(value.getDateTime());
            setNumber(value.getNumber());
            setText(value.getText());
            setTime(value.getTime());
            resetChangedOnNotNull();
        }
    }
}
