/*
 * This file is generated by jOOQ.
 */
package com.parser.core.example.entity.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExampleDict implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private LocalDateTime cdt;
    private UUID createdBy;
    private LocalDateTime mdt;
    private UUID modifiedBy;
    private LocalDateTime rdt;
    private String description;
    private String name;
    private BigDecimal amount;
    private LocalDate date;
    private LocalDateTime dateTime;
    private Long number;
    private String text;
    private LocalTime time;

    public ExampleDict() {}

    public ExampleDict(ExampleDict value) {
        this.id = value.id;
        this.cdt = value.cdt;
        this.createdBy = value.createdBy;
        this.mdt = value.mdt;
        this.modifiedBy = value.modifiedBy;
        this.rdt = value.rdt;
        this.description = value.description;
        this.name = value.name;
        this.amount = value.amount;
        this.date = value.date;
        this.dateTime = value.dateTime;
        this.number = value.number;
        this.text = value.text;
        this.time = value.time;
    }

    public ExampleDict(
        UUID id,
        LocalDateTime cdt,
        UUID createdBy,
        LocalDateTime mdt,
        UUID modifiedBy,
        LocalDateTime rdt,
        String description,
        String name,
        BigDecimal amount,
        LocalDate date,
        LocalDateTime dateTime,
        Long number,
        String text,
        LocalTime time
    ) {
        this.id = id;
        this.cdt = cdt;
        this.createdBy = createdBy;
        this.mdt = mdt;
        this.modifiedBy = modifiedBy;
        this.rdt = rdt;
        this.description = description;
        this.name = name;
        this.amount = amount;
        this.date = date;
        this.dateTime = dateTime;
        this.number = number;
        this.text = text;
        this.time = time;
    }

    /**
     * Getter for <code>public.example_dict.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.example_dict.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.example_dict.cdt</code>.
     */
    public LocalDateTime getCdt() {
        return this.cdt;
    }

    /**
     * Setter for <code>public.example_dict.cdt</code>.
     */
    public void setCdt(LocalDateTime cdt) {
        this.cdt = cdt;
    }

    /**
     * Getter for <code>public.example_dict.created_by</code>.
     */
    public UUID getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.example_dict.created_by</code>.
     */
    public void setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>public.example_dict.mdt</code>.
     */
    public LocalDateTime getMdt() {
        return this.mdt;
    }

    /**
     * Setter for <code>public.example_dict.mdt</code>.
     */
    public void setMdt(LocalDateTime mdt) {
        this.mdt = mdt;
    }

    /**
     * Getter for <code>public.example_dict.modified_by</code>.
     */
    public UUID getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>public.example_dict.modified_by</code>.
     */
    public void setModifiedBy(UUID modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>public.example_dict.rdt</code>.
     */
    public LocalDateTime getRdt() {
        return this.rdt;
    }

    /**
     * Setter for <code>public.example_dict.rdt</code>.
     */
    public void setRdt(LocalDateTime rdt) {
        this.rdt = rdt;
    }

    /**
     * Getter for <code>public.example_dict.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.example_dict.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.example_dict.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.example_dict.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.example_dict.amount</code>.
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>public.example_dict.amount</code>.
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Getter for <code>public.example_dict.date</code>.
     */
    public LocalDate getDate() {
        return this.date;
    }

    /**
     * Setter for <code>public.example_dict.date</code>.
     */
    public void setDate(LocalDate date) {
        this.date = date;
    }

    /**
     * Getter for <code>public.example_dict.date_time</code>.
     */
    public LocalDateTime getDateTime() {
        return this.dateTime;
    }

    /**
     * Setter for <code>public.example_dict.date_time</code>.
     */
    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * Getter for <code>public.example_dict.number</code>.
     */
    public Long getNumber() {
        return this.number;
    }

    /**
     * Setter for <code>public.example_dict.number</code>.
     */
    public void setNumber(Long number) {
        this.number = number;
    }

    /**
     * Getter for <code>public.example_dict.text</code>.
     */
    public String getText() {
        return this.text;
    }

    /**
     * Setter for <code>public.example_dict.text</code>.
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Getter for <code>public.example_dict.time</code>.
     */
    public LocalTime getTime() {
        return this.time;
    }

    /**
     * Setter for <code>public.example_dict.time</code>.
     */
    public void setTime(LocalTime time) {
        this.time = time;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ExampleDict other = (ExampleDict) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.cdt == null) {
            if (other.cdt != null)
                return false;
        }
        else if (!this.cdt.equals(other.cdt))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.mdt == null) {
            if (other.mdt != null)
                return false;
        }
        else if (!this.mdt.equals(other.mdt))
            return false;
        if (this.modifiedBy == null) {
            if (other.modifiedBy != null)
                return false;
        }
        else if (!this.modifiedBy.equals(other.modifiedBy))
            return false;
        if (this.rdt == null) {
            if (other.rdt != null)
                return false;
        }
        else if (!this.rdt.equals(other.rdt))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        if (this.date == null) {
            if (other.date != null)
                return false;
        }
        else if (!this.date.equals(other.date))
            return false;
        if (this.dateTime == null) {
            if (other.dateTime != null)
                return false;
        }
        else if (!this.dateTime.equals(other.dateTime))
            return false;
        if (this.number == null) {
            if (other.number != null)
                return false;
        }
        else if (!this.number.equals(other.number))
            return false;
        if (this.text == null) {
            if (other.text != null)
                return false;
        }
        else if (!this.text.equals(other.text))
            return false;
        if (this.time == null) {
            if (other.time != null)
                return false;
        }
        else if (!this.time.equals(other.time))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.cdt == null) ? 0 : this.cdt.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.mdt == null) ? 0 : this.mdt.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.rdt == null) ? 0 : this.rdt.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        result = prime * result + ((this.dateTime == null) ? 0 : this.dateTime.hashCode());
        result = prime * result + ((this.number == null) ? 0 : this.number.hashCode());
        result = prime * result + ((this.text == null) ? 0 : this.text.hashCode());
        result = prime * result + ((this.time == null) ? 0 : this.time.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ExampleDict (");

        sb.append(id);
        sb.append(", ").append(cdt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(mdt);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(rdt);
        sb.append(", ").append(description);
        sb.append(", ").append(name);
        sb.append(", ").append(amount);
        sb.append(", ").append(date);
        sb.append(", ").append(dateTime);
        sb.append(", ").append(number);
        sb.append(", ").append(text);
        sb.append(", ").append(time);

        sb.append(")");
        return sb.toString();
    }
}
