/*
 * This file is generated by jOOQ.
 */
package com.parser.core.example.entity;


import com.parser.core.example.entity.tables.ExampleDict;
import com.parser.core.example.entity.tables.TestEntity;
import com.parser.core.example.entity.tables.records.ExampleDictRecord;
import com.parser.core.example.entity.tables.records.TestEntityRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ExampleDictRecord> EXAMPLE_DICT_PKEY = Internal.createUniqueKey(ExampleDict.EXAMPLE_DICT, DSL.name("example_dict_pkey"), new TableField[] { ExampleDict.EXAMPLE_DICT.ID }, true);
    public static final UniqueKey<TestEntityRecord> TEST_ENTITY_PKEY = Internal.createUniqueKey(TestEntity.TEST_ENTITY, DSL.name("test_entity_pkey"), new TableField[] { TestEntity.TEST_ENTITY.ID }, true);
}
