/*
 * This file is generated by jOOQ.
 */
package com.parser.core.example.entity;


import com.parser.core.example.entity.tables.ExampleDict;
import com.parser.core.example.entity.tables.TestEntity;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.example_dict</code>.
     */
    public final ExampleDict EXAMPLE_DICT = ExampleDict.EXAMPLE_DICT;

    /**
     * The table <code>public.test_entity</code>.
     */
    public final TestEntity TEST_ENTITY = TestEntity.TEST_ENTITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ExampleDict.EXAMPLE_DICT,
            TestEntity.TEST_ENTITY
        );
    }
}
