/*
 * This file is generated by jOOQ.
 */
package com.parser.core.example.entity;


import com.parser.core.example.entity.tables.ExampleDict;
import com.parser.core.example.entity.tables.TestEntity;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.example_dict</code>.
     */
    public static final ExampleDict EXAMPLE_DICT = ExampleDict.EXAMPLE_DICT;

    /**
     * The table <code>public.test_entity</code>.
     */
    public static final TestEntity TEST_ENTITY = TestEntity.TEST_ENTITY;
}
